### ISSUE TITLE
Publish this plugin to NPM

### ISSUE THREAD

**Issue by tiagoamaro** [lubien/cerebro-reload#1]
Hey @lubien, how are you? :)

Could you publish this to NPM? This is incredibly useful when developing plugins!

Not a huge fan of going to my system tray and going through all menus to click on "reload"!

**Comment by lubien** [comment]
I didn't publish it??
I missed the most important step kkk

**Comment by lubien** [comment]
[Done!](https://www.npmjs.com/package/cerebro-reload)

![image](https://cloud.githubusercontent.com/assets/9121359/23857459/27c5803e-07dc-11e7-848d-bd9cb7c3ee20.png)
