### ISSUE TITLE
Moving plugin to core

### ISSUE THREAD

**Issue by KELiON** [lubien/cerebro-reload#2]
Hey, @lubien! 

I found you plugin in cerebro plugins list and I think it makes sense to move it to the core, because it can be useful for development/debugging/etc.

What do you think about it? I'd appreciate PR to Cerebro. 

You can do it like [quit](https://github.com/KELiON/cerebro/blob/master/app/main/plugins/core/cerebro/quit/index.js) subplugin works now.  Also I've noticed that you just use `location.reload()`, that is not correct, because Cerebro contains two windows: main UI and background, and `location.reload()` will reload only main window. To reload both windows you can do something like:

```js
import { send } from 'lib/rpc/events'

// Send message to reload background window
send('reload')
// Reload main UI window
location.reload()
```

Looking forward for you PR! Let me know if I can help with something

**Comment by lubien** [comment]
I'd love to make a PR! I'll work on this tonight (BRT) so just one question:

Where the plugin should go?

* cerebro/app/main/plugins/core/cerebro/reload/
* cerebro/app/main/plugins/core/reload/

**Comment by lubien** [comment]
Also, as you could have seen, I'm using a creative commons licensed icon here.

Do you prefer to use another icon or this one is fine? Where should I credit the author in your repo if I use this one?

**Comment by KELiON** [comment]
@lubien I prefer to put all Cerebro internal plugins to `cerebro/app/main/plugins/core/cerebro` (so, first option is better). 

Regarding icon – I'd change it to some free icon. Now all internal commands use only one icon (the same as application itself), but now I have another idea: would be great to do some overlay (like gear icon above Cerebro for settings, reload icon above Cerebro icon for reload, etc).

**Comment by lubien** [comment]
Ok. For now I'll use the application one :)
